version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: Budgy
      POSTGRES_PASSWORD: Budgy
      POSTGRES_DB: Budgy_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_HOST: db
      DB_NAME: Budgy_development
      DB_USERNAME: Budgy
      DB_PASSWORD: Budgy
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://Budgy:Budgy@db:5432/Budgy_development

volumes:
  postgres_data:
networks:
  default:
    name: myapp_default
